/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:fb4be54d-8382-4621-acb5-9c93bb5bb2b2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ggV63ZiI6",
    "aws_user_pools_web_client_id": "5io4aeg9uig2msn0orqq02gkt6",
    "oauth": {}
};


export default awsmobile;
